[package]
name = "Ludo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_tokenizers = "7.0.1"
rust-stemmers = "1.2.0"
serde_json = "1.0"
rand = "0.8.5"
nalgebra = "0.30.1"
